openapi: 3.0.1
info:
  title: QuizAPI
  version: '1.0'
paths:
  /api/question/answer:
    post:
      tags:
        - Question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
          text/json:
            schema:
              $ref: '#/components/schemas/Answer'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Answer'
      responses:
        '200':
          description: Success
  /api/question/getquestions:
    post:
      tags:
        - Question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
          text/json:
            schema:
              $ref: '#/components/schemas/Data'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        '200':
          description: Success
components:
  schemas:
    Answer:
      type: object
      properties:
        question:
          type: string
          nullable: true
        subject:
          type: string
          nullable: true
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
          nullable: true
      additionalProperties: false
    Data:
      type: object
      properties:
        characters:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    Option:
      type: object
      properties:
        value:
          type: string
          nullable: true
        checked:
          type: boolean
        isCorrect:
          type: boolean
          nullable: true
      additionalProperties: false
